calculate_global_qTAE_electron_damping_final
calculate_global_qTAE_electron_damping_ini
calculate_global_qTAE_ion_damping_final
calculate_global_qTAE_ion_damping_ini
calculate_global_qTAE_drive_final
calculate_global_qTAE_drive_ini
plot_many_n_modes_TAE_growth_rho
