./compile_run_manyG_precess_eq_post1.sh &
./compile_run_manyG_precess_eq_post2.sh &
./compile_run_manyG_precess_eq_post3.sh &
./compile_run_manyG_precess_eq_post4.sh &
./compile_run_manyG_precess_eq_post5.sh &
./compile_run_manyG_precess_eq_post6.sh &
./compile_run_manyG_precess_eq_post7.sh &
./compile_run_manyG_precess_eq_post8.sh &
./compile_run_manyG_precess_eq_post9.sh &
./compile_run_manyG_precess_eq_post10.sh &
./compile_run_manyG_precess_eq_post11.sh &
./compile_run_manyG_precess_eq_post12.sh &
./compile_run_manyG_precess_eq_post13.sh &
./compile_run_manyG_precess_eq_post14.sh &
./compile_run_manyG_precess_eq_post15.sh &
./compile_run_manyG_precess_eq_post16.sh &
