function input_data_values=importfile_delta(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 11-Mar-2013 15:34:38

DELIMITER = ' ';
HEADERLINES = 2;

% Import the file
input_data = importdata(fileToRead1, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
vars = fieldnames(input_data);
for i = 1:length(vars)
    assignin('base', vars{i}, input_data.(vars{i}));
end

input_data_values=input_data.data;