%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\MATLAB\JET_060513\finesse20130506_195209.501_+0200.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2013/05/07 10:55:48

%% Initialize variables.
filename = 'finesse20180102_151844.357_+0100.dat';
startRow = 3;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%20f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
finesse_data = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars fileID startRow formatSpec dataArray ans;

save finesse_data.mat finesse_data

create_tokamak_withMETISparameters;

disp('----------------------------------------------------------------------------------------')
disp(['[Please double check the value of R0 : ' num2str(a/epsilon)])
disp('----------------------------------------------------------------------------------------')
