%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\MATLAB\AUG_30382_2p5\displacement_dynamics\core_displacement30382_2.513.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/07/07 12:40:04

%% Initialize variables.
filename = 'core_displacement30382_2.934.txt';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%9f%10f%10f%10f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
coredisplacement30382 = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
time_core_evol = coredisplacement30382{:, 1};
Rcore_evol = coredisplacement30382{:, 2};
Zcore_evol = coredisplacement30382{:, 3};
rhopol_core_evol= coredisplacement30382{:, 4};
emission_core_evol = coredisplacement30382{:, 5};

%% Clear temporary variables
clearvars filename formatSpec fileID coredisplacement30382 ans;