./compile_Bpsi_evol1.sh &
./compile_Bpsi_evol2.sh &
./compile_Bpsi_evol3.sh &
./compile_Bpsi_evol4.sh &
./compile_Bpsi_evol5.sh &
./compile_Bpsi_evol6.sh &
./compile_Bpsi_evol7.sh &
./compile_Bpsi_evol8.sh &
./compile_Bpsi_evol9.sh &
./compile_Bpsi_evol10.sh &
./compile_Bpsi_evol11.sh &
./compile_Bpsi_evol12.sh &
./compile_Bpsi_evol13.sh &
./compile_Bpsi_evol14.sh &
./compile_Bpsi_evol15.sh &
./compile_Bpsi_evol16.sh &
